/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        ArrayList<Quotes>quotes=new ArrayList<Quotes>();
        System.out.println(new App().getGreeting());
        //Gson gson=new Gson();
        File file = new File("app/src/main/resources/recentquotes.json");
        try {
            Scanner scanner = new Scanner(file);
            while (scanner.hasNext()){
                System.out.println("read");
            }
        }catch (FileNotFoundException e){
            System.out.println("not");
        }
      // gson.fromJson("app/src/main/resources/recentquotes.json");
        Type typeOfObjectsList = new TypeToken<ArrayList<Quotes>>() {}.getType();
        List<Quotes> objectsList = new Gson().fromJson(String.valueOf(file),typeOfObjectsList);
//Parentquotes oneQuote=gson.fromJson(file,);

        System.out.println(objectsList);
    }
}
